services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: oncall-api
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_RELOAD=true
      - DEBUG=true
      - LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
      - ./api:/app
    networks:
      - oncall-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    container_name: oncall-web
    ports:
      - "3000:3000"
    environment:
      - WEB_PORT=3000
      - WEB_HOST=0.0.0.0
    depends_on:
      api:
        condition: service_healthy
    networks:
      - oncall-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  oncall-network:
    driver: bridge

volumes:
  data:
    driver: local
